spring.application.name=ruta_ya
spring.datasource.url=jdbc:mysql://localhost:3307/proyecto_db
spring.datasource.username=root
spring.datasource.password=mari
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver